### ISSUE TITLE
Pages Tracking for the Website 

### ISSUE THREAD

**Issue by Hamdysaad20** [levelupesg/WebsiteReact#9]
- [x] Home
- [x] Services
  - [x] Main Page
- [x] Solutions
  - [x] Main Page (not Ready Product but we Need to show that it we working on it and we have a perspective of the sections of the dashboard or we have a dashboard)
  - [x] Data management -  after launching the website
  - [x] Purpose-built analytics Services -  after launching the website
  - [x] [Integrations and API](https://greenomy.io/products/apis) )  -  after launching the website
- [x] Partners -  after launching the website
- [x] Learn  -  after launching the website
- [x]  Blogs
- [x] About us
- [x] Join us -  after launching the website
- [x] Contact us
- [x] cookies 
- [x] privacy
- [x] waiting list
